---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-gpu
spec:
  schedule: "5 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
          - name: needpc-scrap-gpu
            image: quay.io/perriea/needpc-scrap:0.0.1
            command:
            - scrap:gpu --trace
          restartPolicy: OnFailure

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-cpu
spec:
  schedule: "20 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
          - name: needpc-scrap-cpu
            image: quay.io/perriea/needpc-scrap:0.0.1
            command:
            - scrap:cpu --trace
          restartPolicy: OnFailure

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-ldlc
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
          - name: needpc-scrap-ldlc
            image: quay.io/perriea/needpc-scrap:0.0.1
            command:
            - scrap:ldlc --trace
          restartPolicy: OnFailure

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-fnac
spec:
  schedule: "30 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
          - name: needpc-scrap-fnac
            image: quay.io/perriea/needpc-scrap:0.0.1
            command:
            - scrap:fnac --trace
          restartPolicy: OnFailure

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-topachat
spec:
  schedule: "40 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
          - name: needpc-scrap-topachat
            image: quay.io/perriea/needpc-scrap:0.0.1
            command:
            - scrap:topchat --trace
          restartPolicy: OnFailure

