version: '3.7'

services:
  db:
    image: postgres:9.6.9-alpine
    hostname: db
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: dev-node
      POSTGRES_USER: node
      POSTGRES_PASSWORD: nodejs
    networks:
      - db-private
      - app-private
    ports:
      - "5432:5432"
  
  redis:
    image: redis:4.0-alpine
    hostname: redis
    environment:
      NODE_ENV: development
    networks:
      - cache-private
      - app-private
    ports:
      - "6379:6379"

  api-computers:
    image: quay.io/needpc/needpc-api-computers:latest
    build: ./micro-services/get-computers
    hostname: api-computers
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: development
      APP_REDIS_HOST: redis
    networks:
      - app-private
    ports:
      - "20006:3000"

  api-activity:
    image: quay.io/needpc/needpc-api-activities:latest
    build: ./micro-services/get-activities
    hostname: api-activity
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: development
      APP_REDIS_HOST: redis
    networks:
      - app-private
    ports:
      - "20005:3000"

  api-ask:
    image: quay.io/needpc/needpc-api-ask:latest
    build: ./micro-services/get-ask
    hostname: api-ask
    depends_on:
      - db
    environment:
      NODE_ENV: development
    networks:
      - app-private
    ports:
      - "20004:3000"

  api-brand:
    image: quay.io/needpc/needpc-api-brands:latest
    build: ./micro-services/get-brands
    hostname: api-brand
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: development
      APP_REDIS_HOST: redis
    networks:
      - app-private
    ports:
      - "20003:3000"

  api-cpu:
    image: quay.io/needpc/needpc-api-cpus:latest
    build: ./micro-services/get-cpus
    hostname: api-cpu
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: development
      APP_REDIS_HOST: redis
    networks:
      - app-private
    ports:
      - "20002:3000"

  api-gpu:
    image: quay.io/needpc/needpc-api-gpus:latest
    build: ./micro-services/get-gpus
    hostname: api-gpu
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: development
      APP_REDIS_HOST: redis
    networks:
      - app-private
    ports:
      - "20001:3000"

  api-notfound:
    image: quay.io/needpc/needpc-api-notfound:latest
    build: ./micro-services/get-notfound
    hostname: api-notfound
    depends_on:
      - db
      - redis
    networks:
      - app-private
    ports:
      - "20000:3000"

  frontend:
    image: quay.io/needpc/needpc-frontend:latest
    build: ./frontend
    hostname: frontend
    networks:
      - app-private
    ports:
      - "19000:80"

  gateway:
    image: nginx:1.15.1-alpine
    build: ./micro-services/gateway
    hostname: gateway
    depends_on:
      - api-computers
      - api-activity
      - api-ask
      - api-brand
      - api-cpu
      - api-gpu
      - api-notfound
      - frontend
    networks:
      - public
      - app-private
    ports:
      - "80:80"

volumes:
    db_data: {}

networks:
  public: {}
  app-private: {}
  db-private: {}
  cache-private: {}