apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    prometheus.io/port: "9101"
    prometheus.io/scrape: "true"
  name: {{ template "frontend.fullname" . }}
  labels:
    app: {{ template "frontend.name" . }}
    chart: {{ template "frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "frontend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "frontend.name" . }}
        release: {{ .Release.Name }}
    spec:
      replicas: 1
      containers:
        - name: {{ .Chart.Name }}
          hostname: {{ .Values.frontend.hostname }}
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          imagePullSecrets:
          - name: {{ .Values.frontend.registry }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
          resources:
{{ toYaml .Values.frontend_resources | indent 12 }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
