---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "frontend.fullname" . }}
  annotations:
    # ingress.kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/tls-acme: "true"
    # certmanager.k8s.io/issuer: letsencrypt-prod
    # certmanager.k8s.io/acme-challenge-type: dns01
    # certmanager.k8s.io/acme-dns01-provider: cf-dns
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - www.needpc.fr
    # secretName: letsencrypt-prod
  rules:
  - host: www.needpc.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "frontend.fullname" . }}
          servicePort: 80