# Default values for gpus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# HPA
minReplicaCount: 1
maxReplicaCount: 4

# Namespace
namespace: needpc-api

# Deployment
gpus:
  hostname: gpus
  repository: quay.io/needpc/needpc-api-gpus
  tag: latest
  pullPolicy: Always
  environment: production
  registry: regcred

redis:
  hostname: redis
  repository: redis
  tag: 4.0-alpine
  pullPolicy: IfNotPresent

# Service
service:
  type: ClusterIP
  containerPort: 3000
  port: 80

gpus_resources:
  limits:
   cpu: 200m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 64Mi

redis_resources:
  limits:
   cpu: 300m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
