---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "activities.fullname" . }}
  annotations:
    # ingress.kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/tls-acme: "true"
    # certmanager.k8s.io/issuer: letsencrypt-prod
    # certmanager.k8s.io/acme-challenge-type: dns01
    # certmanager.k8s.io/acme-dns01-provider: cf-dns
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://www.needpc.fr"
    nginx.ingress.kubernetes.io/cors-allow-methods: "HEAD, GET"
spec:
  tls:
  - hosts:
    - api.needpc.fr
    # secretName: letsencrypt-prod
  rules:
  - host: api.needpc.fr
    http:
      paths:
      - path: /v1/search/activity
        backend:
          serviceName: {{ template "activities.fullname" . }}
          servicePort: 80