# Default values for computers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# HPA
minReplicaCount: 1
maxReplicaCount: 4

# Namespace
namespace: needpc

# Deployment
computers:
  hostname: computers
  repository: quay.io/needpc/needpc-api-computers
  tag: latest
  pullPolicy: Always
  environment: production
  registry: regcred

# Service
service:
  type: ClusterIP
  containerPort: 3000
  port: 80

computers_resources:
  limits:
   cpu: 200m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
