---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-gpu
spec:
  schedule: "5 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
          - name: needpc-scrap-gpu
            image: quay.io/perriea/needpc-scrap:0.0.1
            command:
            - scrap:gpu --trace
          restartPolicy: OnFailure